(PXP-9890): rotate through nightly build environments
uc-cdis/gen3-release-utils pull request #189
Opened 2022-05-06 00:18 UTC by johnfrancismccann

Jira Ticket: [PXP-9890](https://ctds-planx.atlassian.net/browse/PXP-9890)

### Improvements
- Rotate through nightly build environments

2022-05-06 15:01 UTC, paulineribeyre requested changes

2022-05-06 15:17 UTC, johnfrancismccann commented on jenkins-jobs/nightly-job-run.sh
> +selectedCommons=${commons[(seconds / (24*60*60)) % ${#commons[@]} ]}
Yeah I tested it with Bash version `3.2.57(1)-release`

2022-05-10 16:38 UTC, haraprasadj approved these changes

2022-05-11 18:51 UTC, paulineribeyre approved these changes
like i said i don't love it (removing environments) but if it's fine with the QA team it's fine with me

2022-05-11 19:02 UTC, merged